/**
 * Planning Artifact Manager — create, update, and retrieve planning documents.
 *
 * Port of OpenAI Codex's Plan.md/Implement.md/Documentation.md pattern.
 * Manages durable, version-controlled planning documents for long-horizon
 * tasks that exceed a single context window.
 *
 * Planning artifacts serve as external memory for the agent: milestones,
 * tasks, and progress are persisted in markdown files that survive context
 * compaction and can be resumed across sessions.
 */

import fs from "node:fs";
import path from "node:path";

import type {
  CreateArtifactOptions,
  Milestone,
  PlanningArtifact,
  PlanningConfig,
  PlanningTask,
  UpdateArtifactOptions,
} from "./types.js";
import { DEFAULT_PLANNING_CONFIG } from "./types.js";

/** Generate a unique ID. */
function generateId(prefix: string): string {
  return `${prefix}_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
}

/** Serialize milestones to markdown. */
function milestonesToMarkdown(milestones: Milestone[]): string {
  if (milestones.length === 0) return "";

  const lines: string[] = ["## Milestones\n"];
  for (const m of milestones) {
    const checkbox = m.status === "completed" ? "[x]" : m.status === "in_progress" ? "[~]" : "[ ]";
    lines.push(`### ${checkbox} ${m.title}`);
    lines.push(`Status: ${m.status} | ID: ${m.id}\n`);
    if (m.description) {
      lines.push(`${m.description}\n`);
    }
    if (m.dependencies.length > 0) {
      lines.push(`**Dependencies:** ${m.dependencies.join(", ")}\n`);
    }
    if (m.tasks.length > 0) {
      lines.push("**Tasks:**");
      for (const t of m.tasks) {
        const tCheckbox = t.status === "completed" ? "[x]" : t.status === "in_progress" ? "[~]" : "[ ]";
        lines.push(`  - ${tCheckbox} ${t.title} (${t.status})`);
      }
      lines.push("");
    }
  }
  return lines.join("\n");
}

/** Generate default Plan.md content. */
function generatePlanContent(title: string, milestones: Milestone[]): string {
  return `# ${title}\n\n> Generated by Quill Planning Artifacts\n\n${milestonesToMarkdown(milestones)}`;
}

/** Generate default Implement.md content. */
function generateImplementContent(title: string): string {
  return `# Implementation: ${title}\n\n> Detailed implementation steps and progress.\n\n## Steps\n\n## Notes\n`;
}

/** Generate default Documentation.md content. */
function generateDocumentationContent(title: string): string {
  return `# Documentation: ${title}\n\n> Auto-generated documentation and decisions.\n\n## Architecture Decisions\n\n## API Reference\n\n## Notes\n`;
}

/**
 * Planning Artifact Manager.
 *
 * Creates, updates, and retrieves planning documents for long-horizon tasks.
 * Artifacts are stored as markdown files with structured metadata.
 */
export class PlanningArtifactManager {
  private config: PlanningConfig;
  private artifacts = new Map<string, PlanningArtifact>();

  constructor(config: Partial<PlanningConfig> = {}) {
    this.config = { ...DEFAULT_PLANNING_CONFIG, ...config };
  }

  /**
   * Create a new planning artifact.
   */
  create(options: CreateArtifactOptions): PlanningArtifact {
    const now = Date.now();
    const content =
      options.content ??
      (options.type === "plan"
        ? generatePlanContent(options.title, options.milestones ?? [])
        : options.type === "implement"
          ? generateImplementContent(options.title)
          : generateDocumentationContent(options.title));

    const artifact: PlanningArtifact = {
      type: options.type,
      threadId: options.threadId,
      runId: options.runId ?? null,
      title: options.title,
      content,
      milestones: options.milestones ?? [],
      version: 1,
      createdAt: now,
      updatedAt: now,
      archived: false,
    };

    this.artifacts.set(this.artifactKey(options.threadId, options.type), artifact);
    return { ...artifact };
  }

  /**
   * Get a planning artifact by thread and type.
   */
  get(threadId: string, type: PlanningArtifact["type"]): PlanningArtifact | null {
    const artifact = this.artifacts.get(this.artifactKey(threadId, type));
    return artifact ? { ...artifact } : null;
  }

  /**
   * Get all artifacts for a thread.
   */
  getByThread(threadId: string): PlanningArtifact[] {
    return [...this.artifacts.values()]
      .filter((a) => a.threadId === threadId && !a.archived)
      .map((a) => ({ ...a }));
  }

  /**
   * Update a planning artifact.
   */
  update(
    threadId: string,
    type: PlanningArtifact["type"],
    updates: UpdateArtifactOptions,
  ): PlanningArtifact | null {
    const key = this.artifactKey(threadId, type);
    const artifact = this.artifacts.get(key);
    if (!artifact) return null;

    const updated: PlanningArtifact = {
      ...artifact,
      ...updates,
      version: artifact.version + 1,
      updatedAt: Date.now(),
    };

    this.artifacts.set(key, updated);
    return { ...updated };
  }

  /**
   * Add a milestone to a plan artifact.
   */
  addMilestone(
    threadId: string,
    milestone: Omit<Milestone, "id">,
  ): PlanningArtifact | null {
    const plan = this.get(threadId, "plan");
    if (!plan) return null;

    const newMilestone: Milestone = {
      ...milestone,
      id: generateId("ms"),
    };

    const milestones = [...plan.milestones, newMilestone];
    return this.update(threadId, "plan", {
      milestones,
      content: generatePlanContent(plan.title, milestones),
    });
  }

  /**
   * Update a milestone's status.
   */
  updateMilestoneStatus(
    threadId: string,
    milestoneId: string,
    status: Milestone["status"],
  ): PlanningArtifact | null {
    const plan = this.get(threadId, "plan");
    if (!plan) return null;

    const milestones = plan.milestones.map((m) =>
      m.id === milestoneId
        ? {
            ...m,
            status,
            completedAt: status === "completed" ? Date.now() : m.completedAt,
          }
        : m,
    );

    return this.update(threadId, "plan", {
      milestones,
      content: generatePlanContent(plan.title, milestones),
    });
  }

  /**
   * Add a task to a milestone.
   */
  addTaskToMilestone(
    threadId: string,
    milestoneId: string,
    task: Omit<PlanningTask, "id">,
  ): PlanningArtifact | null {
    const plan = this.get(threadId, "plan");
    if (!plan) return null;

    const newTask: PlanningTask = {
      ...task,
      id: generateId("task"),
    };

    const milestones = plan.milestones.map((m) =>
      m.id === milestoneId ? { ...m, tasks: [...m.tasks, newTask] } : m,
    );

    return this.update(threadId, "plan", {
      milestones,
      content: generatePlanContent(plan.title, milestones),
    });
  }

  /**
   * Update a task's status.
   */
  updateTaskStatus(
    threadId: string,
    milestoneId: string,
    taskId: string,
    status: PlanningTask["status"],
  ): PlanningArtifact | null {
    const plan = this.get(threadId, "plan");
    if (!plan) return null;

    const milestones = plan.milestones.map((m) =>
      m.id === milestoneId
        ? {
            ...m,
            tasks: m.tasks.map((t) =>
              t.id === taskId
                ? {
                    ...t,
                    status,
                    completedAt: status === "completed" ? Date.now() : t.completedAt,
                  }
                : t,
            ),
          }
        : m,
    );

    return this.update(threadId, "plan", {
      milestones,
      content: generatePlanContent(plan.title, milestones),
    });
  }

  /**
   * Archive a planning artifact.
   */
  archive(threadId: string, type: PlanningArtifact["type"]): PlanningArtifact | null {
    const key = this.artifactKey(threadId, type);
    const artifact = this.artifacts.get(key);
    if (!artifact) return null;

    const updated: PlanningArtifact = {
      ...artifact,
      archived: true,
      updatedAt: Date.now(),
    };

    this.artifacts.set(key, updated);
    return { ...updated };
  }

  /**
   * Get progress summary for a plan.
   */
  getProgress(threadId: string): {
    totalMilestones: number;
    completedMilestones: number;
    totalTasks: number;
    completedTasks: number;
    percentComplete: number;
  } | null {
    const plan = this.get(threadId, "plan");
    if (!plan) return null;

    const totalMilestones = plan.milestones.length;
    const completedMilestones = plan.milestones.filter(
      (m) => m.status === "completed",
    ).length;
    const totalTasks = plan.milestones.reduce((sum, m) => sum + m.tasks.length, 0);
    const completedTasks = plan.milestones.reduce(
      (sum, m) => sum + m.tasks.filter((t) => t.status === "completed").length,
      0,
    );

    const totalItems = totalMilestones + totalTasks;
    const completedItems = completedMilestones + completedTasks;

    return {
      totalMilestones,
      completedMilestones,
      totalTasks,
      completedTasks,
      percentComplete: totalItems > 0 ? Math.round((completedItems / totalItems) * 100) : 0,
    };
  }

  /**
   * Persist artifacts to disk.
   */
  async persist(): Promise<void> {
    for (const artifact of this.artifacts.values()) {
      const filePath = this.getArtifactPath(artifact.threadId, artifact.type);
      try {
        fs.mkdirSync(path.dirname(filePath), { recursive: true });
        fs.writeFileSync(filePath, artifact.content, "utf-8");
      } catch (err) {
        console.error(`[planning] Failed to persist artifact: ${err instanceof Error ? err.message : err}`);
      }
    }
  }

  /**
   * Load artifacts from disk.
   */
  async load(threadId: string): Promise<void> {
    for (const type of ["plan", "implement", "documentation"] as const) {
      const filePath = this.getArtifactPath(threadId, type);
      try {
        if (fs.existsSync(filePath)) {
          const content = fs.readFileSync(filePath, "utf-8");
          // Basic parsing: extract milestones from markdown.
          const milestones = this.parseMilestonesFromMarkdown(content);
          const artifact: PlanningArtifact = {
            type,
            threadId,
            runId: null,
            title: this.extractTitle(content) || `${type}.md`,
            content,
            milestones,
            version: 1,
            createdAt: fs.statSync(filePath).birthtimeMs,
            updatedAt: fs.statSync(filePath).mtimeMs,
            archived: false,
          };
          this.artifacts.set(this.artifactKey(threadId, type), artifact);
        }
      } catch (err) {
        console.error(`[planning] Failed to load artifact: ${err instanceof Error ? err.message : err}`);
      }
    }
  }

  /**
   * Get the storage path for an artifact.
   */
  private getArtifactPath(threadId: string, type: PlanningArtifact["type"]): string {
    return path.join(this.config.storageDir, threadId, `${type}.md`);
  }

  /**
   * Generate the storage key for an artifact.
   */
  private artifactKey(threadId: string, type: PlanningArtifact["type"]): string {
    return `${threadId}:${type}`;
  }

  /**
   * Extract title from markdown content.
   */
  private extractTitle(content: string): string | null {
    const match = content.match(/^#\s+(.+)$/m);
    return match ? match[1].trim() : null;
  }

  /**
   * Parse milestones from markdown content (basic parser).
   */
  private parseMilestonesFromMarkdown(content: string): Milestone[] {
    const milestones: Milestone[] = [];
    const lines = content.split("\n");
    let currentMilestone: Partial<Milestone> | null = null;

    for (const line of lines) {
      // Match ### headings as milestones.
      const msMatch = line.match(/^###\s+\[([ x~])\]\s+(.+)$/);
      if (msMatch) {
        if (currentMilestone && currentMilestone.title) {
          milestones.push(currentMilestone as Milestone);
        }
        const statusChar = msMatch[1];
        currentMilestone = {
          id: generateId("ms"),
          title: msMatch[2].trim(),
          description: "",
          status: statusChar === "x" ? "completed" : statusChar === "~" ? "in_progress" : "pending",
          tasks: [],
          dependencies: [],
        };
        continue;
      }

      // Match task items.
      if (currentMilestone && line.match(/^\s+-\s+\[([ x~])\]\s+(.+)$/)) {
        const taskMatch = line.match(/^\s+-\s+\[([ x~])\]\s+(.+)$/);
        if (taskMatch) {
          const statusChar = taskMatch[1];
          currentMilestone.tasks = currentMilestone.tasks ?? [];
          currentMilestone.tasks.push({
            id: generateId("task"),
            title: taskMatch[2].trim(),
            description: "",
            status: statusChar === "x" ? "completed" : statusChar === "~" ? "in_progress" : "pending",
          });
        }
      }
    }

    if (currentMilestone && currentMilestone.title) {
      milestones.push(currentMilestone as Milestone);
    }

    return milestones;
  }

  /**
   * Clear all artifacts (for testing).
   */
  clear(): void {
    this.artifacts.clear();
  }
}

/** Singleton manager instance. */
let _manager: PlanningArtifactManager | null = null;

export function getPlanningManager(
  config?: Partial<PlanningConfig>,
): PlanningArtifactManager {
  if (!_manager) {
    _manager = new PlanningArtifactManager(config);
  }
  return _manager;
}

export function resetPlanningManager(): void {
  _manager = null;
}
